---
---
<!-- the two formats are html and revealjs -->

# Clicker Q

to go with **Introduction to Modern Statistics** by Çentinkaya-Rundel & Hardin.  Math 58B - Introduction to Biostatistics.

```{=html}
<style>
.reveal ol ol {
   list-style-type: lower-alpha;
}
</style>
```


---

1. If 16 infants with **no genuine preference** choose 16 toys, what is the most likely number of "helping" toys that will be chosen?[^1]
   (a)	4
   (b)	7
   (c)	8
   (d)	9
   (e)	10


[^1]:  c.	8

---

2. How likely is it that exactly 8 helpers will be chosen (if there is no preference)?[^2]
   (a)	0-15% 
   (b)	16-30% 
   (c)	31-49%
   (d)	50%
   (e)	51-100%


[^2]:  b. 0.196 (19.6% of the time)

---

3. What if we flipped a coin 160 times?  What percent of the time will the simulation flip exactly 80 heads?[^3]
   (a)	0-15% 
   (b)	16-30% 
   (c)	31-49%
   (d)	50%
   (e)	51-100%

[^3]: a. 0.063 (6.3% of the time)

---

4. Is our actual result of 14 (under the coin model)...[^4]
   (a) very surprising?
   (b) somewhat surprising?
   (c) not very surprising?
   
[^4]: a. very surprising (prob of 14 or more is 0.0021)

---

5. Suppose that we record the midterm exam score and the final exam score for every student in a class.  What would the value of the correlation coefficient be if every student in the class scored ten points higher on the final than on the midterm:[^5]
    (a) r = -1
    (b) -1 < r < 0
    (c) r = 0
    (d) 0 < r < 1
    (e) r = 1

[^5]: e. r = 1

---

6. Suppose that we record the midterm exam score and the final exam score for every student in a class.  What would the value of the correlation coefficient be if every student in the class scored five points lower on the final than on the midterm:[^6]
    (a) r = -1
    (b) -1 < r < 0
    (c) r = 0
    (d) 0 < r < 1
    (e) r = 1
    
[^6]: e. r = 1

---

7. Suppose that we record the midterm exam score and the final exam score for every student in a class.  What would the value of the correlation coefficient be if every student in the class scored twice as many points on the final than on the midterm:[^7]
   (a) r = -1
   (b) -1 < r < 0
   (c) r = 0
   (d) 0 < r < 1
   (e) r = 1

[^7]: e. r = 1

---

8. Suppose you guessed every value correctly (guess the correlation applet), what would be the value of the correlation coefficient between your guesses and the actual correlations?[^8]
   (a) r = -1
   (b) -1 < r < 0
   (c) r = 0
   (d) 0 < r < 1
   (e) r = 1

[^8]: e. r = 1

---

9. Suppose each of your guesses was too high by 0.2 from the actual value of the correlation coefficient, what would be the value of the correlation coefficient between your guesses and the actual correlations?[^9]
   (a) r = -1
   (b) -1 < r < 0
   (c) r = 0
   (d) 0 < r < 1
   (e) r = 1

[^9]: e. r = 1

---

10. A correlation coefficient equal to 1 indicates that you are a good guesser.[^10]
    (a) TRUE
    (b) FALSE

[^10]: b. FALSE.  You could get every single value wrong and still have a correlation of one.

---

11. Perfect Correlation... if not for a single outlier  
n = 101 observations:  1 observation in top left, 25 observations in each in of the points near the bottom right.    
The value of the correlation, r, is:[^11]
    (a)	-1   < r < -0.9
    (b)	-0.9 < r < -0.5
    (c)	-0.5 < r <  0.5
    (d)	 0.5 < r <  0.9
    (e)	 0.9 < r <  1


[^11]: c. r = -0.416    
---

```{r}
#| echo: false
#| warning: false
#| message: false
#| 
x_value <- c(rep(17, 25), rep(18, 25), rep(19, 25), rep(20, 25), 1)
y_value <- c(rep(1, 25), rep(2, 25), rep(3, 25), rep(4, 25), 20)

#cor(x_value, y_value)
library(ggplot2)
ggplot(data.frame(x_value, y_value)) + 
  geom_point(aes(x = x_value, y = y_value)) +
  theme(aspect.ratio = 1)
```



---

12. The sum of residuals from the sample mean (no X):[^12] 
$$\sum_{i=1}^n(Y_i - \overline{Y})$$
    (a) is positive
    (b) is negative
    (c) is zero
    (d) is different for every dataset

[^12]: c. always zero

---

13. A good measure of how well the prediction (of the sample mean) fits the data is:[^13]
    (a) $\sum_{i=1}^n(Y_i - \overline{Y})$
    (b) $\sum_{i=1}^n(Y_i - \overline{Y})^2$
    (c) $\sum_{i=1}^n|Y_i - \overline{Y}|$
    (d) $\mbox{median}(Y_i - \overline{Y})$
    (e) $\mbox{median}|Y_i - \overline{Y}|$

[^13]: we usually use b. $\sum_{i=1}^n(Y_i - \overline{Y})^2$ (for calculus and historical reasons), but c. and e. are also totally reasonably answers.

---


14. A good measure of how well the prediction (of the sample mean) fits the data is:[^14]
    (a) $\sum_{i=1}^n(Y_i - \hat{Y}_i)$
    (b) $\sum_{i=1}^n(Y_i - \hat{Y}_i)^2$
    (c) $\sum_{i=1}^n|Y_i - \hat{Y}_i|$
    (d) $\mbox{median}(Y_i -\hat{Y}_i)$
    (e) $\mbox{median}|Y_i -\hat{Y}_i|$

[^14]: we usually use b. $\sum_{i=1}^n(Y_i - \hat{Y}_i)^2$ (for calculus and historical reasons), but c. and e. are also totally reasonably answers.

---

15. What math is used to find the value of $m$ that minimizes:[^15]
$$\sum_{i=1}^n(Y_i - m)^2$$
    (a) combinatorics
    (b) derivative
    (c) integral
    (d) linear algebra

[^15]: b. derivative

---

16. $\sum_i(Y_i - \overline{Y})^2$ is sometimes $\geq \sum_i(Y_i - \hat{Y}_i)^2$[^16]

    a. TRUE
    b. FALSE, $\sum_i(Y_i - \overline{Y})^2$ is always $\geq \sum_i(Y_i - \hat{Y}_i)^2$
    c. FALSE, $\sum_i(Y_i - \overline{Y})^2$ is never $\geq \sum_i(Y_i - \hat{Y}_i)^2$

[^16]: b. FALSE, $\sum_i(Y_i - \overline{Y})^2$ is always $\geq \sum_i(Y_i - \hat{Y}_i)^2$

---

17. When writing the regression equation, why is there a hat ( ^) on the response variable?[^17]
    (a) because the prediction is an estimate
    (b) because the prediction is an average
    (c) because the prediction may be due to extrapolation
    (d) a & b
    (e) all of the above

[^17]: d. due to estimation and average

---







