<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.256">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="your name here">
<meta name="dcterms.date" content="2023-04-25">

<title>Introduction to Biostatistics - Lab 12 - Math 58B: Multiple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/favicon.ico" rel="icon">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="https://m58-intro-stats.netlify.app/" class="navbar-brand navbar-brand-logo">
    <img src="../images/st47s.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="https://m58-intro-stats.netlify.app/">
    <span class="navbar-title">Introduction to Biostatistics</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html">
 <span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notes.html">
 <span class="menu-text">Class Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../project.html">
 <span class="menu-text">Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../clicker_study.html">
 <span class="menu-text">Clicker Q</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 12 - Math 58B: Multiple Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>your name here </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 25, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="lab-goals" class="level3">
<h3 class="anchored" data-anchor-id="lab-goals">Lab Goals</h3>
<ul>
<li>a full analysis including multiple variables</li>
<li>including inference in the linear model</li>
<li>checking technical conditions using scatter plots (more generally, residual plots are used to check technical conditions when there are multiple explanatory variables, but we ran out of time to fully cover residual plots)</li>
<li>choosing variables for the multiple linear regression</li>
</ul>
<section id="grading-the-professor" class="level4">
<h4 class="anchored" data-anchor-id="grading-the-professor">Grading the professor</h4>
<p>Many college courses conclude by giving students the opportunity to evaluate the course and the instructor anonymously. However, the use of these student evaluations as an indicator of course quality and teaching effectiveness is often criticized because these measures may reflect the influence of non-teaching related characteristics, such as the physical appearance of the instructor. The research found that instructors who are viewed to be better looking receive higher instructional ratings.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</section>
<section id="the-data" class="level4">
<h4 class="anchored" data-anchor-id="the-data">The data</h4>
<p>The data were gathered from end of semester student evaluations for a large sample of professors at the University of Texas, Austin. Additionally, six students rated the professors’ physical appearance.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> In the resulting data frame, each row represents a different course and columns represent variables about the courses and professors.</p>
<table class="table">
<colgroup>
<col style="width: 19%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">variable</th>
<th style="text-align: left;">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>score</code></td>
<td style="text-align: left;">average professor evaluation score: (1) very unsatisfactory - (5) excellent.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>rank</code></td>
<td style="text-align: left;">rank of professor: teaching, tenure track, tenured.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>ethnicity</code></td>
<td style="text-align: left;">ethnicity of professor: not minority, minority.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>gender</code></td>
<td style="text-align: left;">gender of professor: female, male.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>language</code></td>
<td style="text-align: left;">language of school where professor received education: English or non-English.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>age</code></td>
<td style="text-align: left;">age of professor.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>cls_perc_eval</code></td>
<td style="text-align: left;">percent of students in class who completed evaluation.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>cls_did_eval</code></td>
<td style="text-align: left;">number of students in class who completed evaluation.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>cls_students</code></td>
<td style="text-align: left;">total number of students in class.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>cls_level</code></td>
<td style="text-align: left;">class level: lower, upper.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>cls_profs</code></td>
<td style="text-align: left;">number of professors teaching sections in course in sample: single, multiple.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>cls_credits</code></td>
<td style="text-align: left;">number of credits of class: one credit (lab, PE, etc.), multi-credit.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>bty_f1lower</code></td>
<td style="text-align: left;">beauty rating of professor from lower level female: (1) lowest - (10) highest.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>bty_f1upper</code></td>
<td style="text-align: left;">beauty rating of professor from upper level female: (1) lowest - (10) highest.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>bty_f2upper</code></td>
<td style="text-align: left;">beauty rating of professor from second upper level female: (1) lowest - (10) highest.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>bty_m1lower</code></td>
<td style="text-align: left;">beauty rating of professor from lower level male: (1) lowest - (10) highest.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>bty_m1upper</code></td>
<td style="text-align: left;">beauty rating of professor from upper level male: (1) lowest - (10) highest.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>bty_m2upper</code></td>
<td style="text-align: left;">beauty rating of professor from second upper level male: (1) lowest - (10) highest.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>bty_avg</code></td>
<td style="text-align: left;">average beauty rating of professor.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>pic_outfit</code></td>
<td style="text-align: left;">outfit of professor in picture: not formal, formal.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>pic_color</code></td>
<td style="text-align: left;">color of professor’s picture: color, black &amp; white.</td>
</tr>
</tbody>
</table>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>evals <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www.openintro.org/data/csv/evals.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data">Exploring the data</h2>
<ol type="1">
<li><p>What are the observational units in this study?</p></li>
<li><p>Is this an observational study or an experiment? The original research question posed in the paper is whether beauty leads directly to the differences in course evaluations. Given the study design, is it possible to answer this question as it is phrased? If not, rephrase the question.</p></li>
<li><p>Describe the distribution of <code>score</code>. Is the distribution skewed? What does that tell you about how students rate courses? Is this what you expected to see? Why, or why not?</p></li>
<li><p>Excluding <code>score</code>, select two other variables and describe their relationship using an appropriate visualization (scatterplot, side-by-side boxplots, barplot, or histogram).</p></li>
</ol>
</section>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">Simple linear regression</h2>
<p>The fundamental phenomenon suggested by the study is that better looking teachers are evaluated more favorably. Let’s create a scatterplot to see if this appears to be the case:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(evals) <span class="sc">+</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> bty_avg, <span class="at">y =</span> score))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lab12_m58_s23_MLR_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Before we draw conclusions about the trend, compare the number of observations in the data frame with the approximate number of points on the scatterplot. Is anything awry?</p>
<p>It is hard to count the points, but we can definitely see some patterns that seem to have more to do with the data collection than the effect. That is, <code>bty_avg</code> is only scored on a few different values (similar for <code>score</code>, but less so).</p>
<ol start="5" type="1">
<li><p>Replot the scatterplot, but this time use the layer <code>geom_jitter()</code>. What was misleading about the initial scatterplot?</p></li>
<li><p>Let’s see if the apparent trend in the plot is something more than natural variation. Fit a linear model called <code>m_bty</code> to predict average professor score by average beauty rating and add the line to your plot using <code>geom_smooth(method = "lm")</code>. Write out the equation for the linear model and interpret the slope. Is average beauty score a statistically significant predictor? Does it appear to be a practically significant predictor?</p></li>
</ol>
<p><span class="math display">\[\begin{eqnarray*}
\widehat{score} &amp;=&amp; b_0 + b_1 \times bty\_avg \\
&amp;=&amp; 3.88 + 0.067 \times bty\_avg
\end{eqnarray*}\]</span></p>
<p>The line is pretty flat (despite having a significant p-value). That is, for every additional point of beauty, a professor’s score is predicted to be 0.067 higher on average. (The increase really isn’t very much.)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>m_bty <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> bty_avg, <span class="at">data =</span> evals)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>m_bty <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   3.88      0.0761     51.0  1.56e-191
2 bty_avg       0.0666    0.0163      4.09 5.08e-  5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(evals, <span class="fu">aes</span>(<span class="at">x =</span> bty_avg, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lab12_m58_s23_MLR_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<ol start="7" type="1">
<li>Instead use the scatter plot to discuss whether you think the technical conditions are met. If you want to know more about residual plots, I’m happy to discuss! [Use residual plots to evaluate whether the conditions of least squares regression are reasonable. Provide plots and comments on whether the linear model seems reasonable here.]</li>
</ol>
<p>Note that the <code>augment()</code> function will give you residuals (<code>.resid</code>) as well as predicted values (<code>.fitted</code>). Once you have the observations, you can plot them using <code>ggplot()</code>. Put <code>.resid</code> on the y-axis and <code>.fitted</code> on the x-axis. You might also use <code>+ geom_hline(yintercept = 0)</code> to add a horizontal line at zero.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>m_bty <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 463 × 8
   score bty_avg .fitted   .resid    .hat .sigma      .cooksd .std.resid
   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
 1   4.7    5       4.21  0.486   0.00247  0.535 0.00103         0.911  
 2   4.1    5       4.21 -0.114   0.00247  0.535 0.0000560      -0.213  
 3   3.9    5       4.21 -0.314   0.00247  0.535 0.000427       -0.587  
 4   4.8    5       4.21  0.586   0.00247  0.535 0.00149         1.10   
 5   4.6    3       4.08  0.520   0.00403  0.535 0.00192         0.974  
 6   4.3    3       4.08  0.220   0.00403  0.535 0.000343        0.412  
 7   2.8    3       4.08 -1.28    0.00403  0.532 0.0116         -2.40   
 8   4.1    3.33    4.10 -0.00244 0.00325  0.535 0.0000000340   -0.00457
 9   3.4    3.33    4.10 -0.702   0.00325  0.534 0.00282        -1.32   
10   4.5    3.17    4.09  0.409   0.00361  0.535 0.00106         0.765  
# ℹ 453 more rows</code></pre>
</div>
</div>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">Multiple linear regression</h2>
<p>What about the model that includes <code>bty_avg</code> and <code>gender</code>? Instead, use a scatterplot where you’ve colored by gender. Does your scatterplot indicate that the technical conditions are met? [Does the residual plot meet the technical conditions?]</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>m_bty_gen <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> bty_avg <span class="sc">+</span> gender, <span class="at">data =</span> evals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="8" type="1">
<li>P-values and parameter estimates should only be trusted if the conditions for the regression are reasonable. Instead, use a scatterplot where you’ve colored by gender. Does your scatterplot indicate that the technical conditions are met?<br>
[Does the residual plot meet the technical conditions? Verify that the conditions for this model are reasonable using a residual plot. Make a residual plot to assess the technical conditions (remember to pipe the linear model into the <code>augment()</code> function).] To force the lines to be parallel, you need a function from the <strong>moderndive</strong> package.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>evals <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> bty_avg, <span class="at">y =</span> score, <span class="at">color =</span> gender)) <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  moderndive<span class="sc">::</span><span class="fu">geom_parallel_slopes</span>(<span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lab12_m58_s23_MLR_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<ol start="9" type="1">
<li>With <code>gender</code> in the model, is <code>bty_avg</code> still a significant predictor of <code>score</code>? Has the addition of <code>gender</code> to the model changed the parameter estimate for <code>bty_avg</code>? (Find the model and pipe it into the <code>tidy()</code> output.)</li>
</ol>
<p>Note that the estimate for <code>gender</code> is now called <code>gendermale</code>. You’ve already see this name change whenever you introduce a categorical variable. The reason is that R recodes <code>gender</code> from having the values of <code>female</code> and <code>male</code> to being an indicator variable called <code>gendermale</code> that takes a value of <span class="math inline">\(0\)</span> for females and a value of <span class="math inline">\(1\)</span> for males. (Such variables are often referred to as “dummy” variables.)</p>
<p>As a result, for females, the parameter estimate is multiplied by zero, leaving the intercept and slope form familiar from simple regression.</p>
<p><span class="math display">\[\begin{eqnarray*}
\widehat{score}_F &amp;=&amp; b_0 + b_1 \times bty\_avg + b_2 \times (0) \\
&amp;=&amp; b_0 + b_1 \times bty\_avg
\end{eqnarray*}\]</span></p>
<ol start="10" type="1">
<li>What is the equation of the line corresponding to males? (<em>Hint:</em> For males, the parameter estimate is multiplied by 1.) For two professors who received the same beauty rating, which gender tends to have the higher course evaluation score?</li>
</ol>
<p>The decision to call the indicator variable <code>gendermale</code> instead of<code>genderfemale</code> has no deep meaning. R simply codes the category that comes first alphabetically as a <span class="math inline">\(0\)</span>. (Advanced R topic: You can change the reference level of a categorical variable, which is the level that is coded as a 0, using the<code>relevel</code> function. Use <code>?relevel</code> to learn more.)</p>
<p>Let’s visualize the two different models on the plot. Seemingly, the best fit linear model has a <strong>different</strong> intercept and a <strong>different</strong> slope across the two genders!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>evals <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> bty_avg, <span class="at">y =</span> score, <span class="at">color =</span> gender)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lab12_m58_s23_MLR_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<ol start="11" type="1">
<li>[Optional: only do this if you are curious about the model which allows for different slopes for the categorical variable. It’s fun and not very hard!!!] Create a new model predicting score by multiplying <code>bty_avg</code> and <code>gender</code>. Write down (separately) the the equation of the line corresponding to females and males? (<em>Hint:</em> For males, the parameter estimate is multiplied by 1.) You will have two equations. Do your two equations have different slopes? Do the equations of the line match the plot above? Multiplying two variables together produces what we call interaction.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>m_bty_gen_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> bty_avg <span class="sc">*</span> gender, <span class="at">data =</span> evals)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>m_bty_gen_int <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term               estimate std.error statistic   p.value
  &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)          3.95      0.118      33.5  2.92e-125
2 bty_avg              0.0306    0.0240      1.28 2.02e-  1
3 gendermale          -0.184     0.153      -1.20 2.32e-  1
4 bty_avg:gendermale   0.0796    0.0325      2.45 1.46e-  2</code></pre>
</div>
</div>
<p><span class="math display">\[\begin{eqnarray*}
\widehat{score}_F &amp;=&amp; b_0 + b_1 \times bty\_avg + b_2 \times (0) + b_3 \times bty\_avg \times (0)\\
&amp;=&amp; b_0 + b_1 \times bty\_avg\\
&amp;=&amp; 3.95 + 0.031 \times bty\_avg
\end{eqnarray*}\]</span></p>
<p><span class="math display">\[\begin{eqnarray*}
\widehat{score}_M &amp;=&amp; b_0 + b_1 \times bty\_avg + b_2 \times (1) + b_3 \times bty\_avg \times (1)\\
&amp;=&amp; (b_0 + b_2) + (b_1 + b_3) \times bty\_avg\\
&amp;=&amp; (3.95 - 0.1835) + (0.031 + 0.0796) \times bty\_avg\\
&amp;=&amp; (3.7665) + (0.1106) \times bty\_avg
\end{eqnarray*}\]</span></p>
<ol start="12" type="1">
<li>[Still optional: extension of 11] Create a new model called <code>m_bty_rank</code> with <code>gender</code> removed and <code>rank</code> added in. How does R appear to handle categorical variables that have more than two levels? Note that the rank variable has three levels: <code>teaching</code>, <code>tenure track</code>, <code>tenured</code>. Write down the three separate models for teach rank. Make a scatterplot to suggest whether <code>bty_avg</code> seem to interact. If so, run an interaction model.</li>
</ol>
<p>There are now <strong>three</strong> models, one for each rank of the professor!</p>
<p><span class="math display">\[\begin{eqnarray*}
\widehat{score}_{teach} &amp;=&amp; b_0 + b_1 \times bty\_avg + b_2 \times (0)  + b_3 \times (0) \\
&amp;=&amp; b_0 + b_1 \times bty\_avg\\
\widehat{score}_{tt} &amp;=&amp; b_0 + b_1 \times bty\_avg + b_2 \times (1) + b_3 \times (0)\\
&amp;=&amp; (b_0 + b_2) + b_1 \times bty\_avg\\
\widehat{score}_{tenured} &amp;=&amp; b_0 + b_1 \times bty\_avg + b_2 \times (0) + b_3 \times (1)\\
&amp;=&amp; (b_0 + b_3) + b_1 \times bty\_avg
\end{eqnarray*}\]</span></p>
<blockquote class="blockquote">
<p>The interpretation of the coefficients in multiple regression is slightly different from that of simple regression. The estimate for <code>bty_avg</code> reflects how much higher a group of professors is expected to score if they have a beauty rating that is one point higher <em>while holding all other variables constant</em>. In this case, that translates into considering only professors of the same rank with <code>bty_avg</code> scores that are one point apart.</p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>evals <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> bty_avg, <span class="at">y =</span> score, <span class="at">color =</span> rank)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lab12_m58_s23_MLR_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>From the plot, it doesn’t really seem like there is much interaction (that is, the lines seem mostly parallel), but we could run the model (using <code>lm()</code>) to see if the interaction terms are significant or not. From the model below, the p-values are not significant, and confirm the plot indicating that interaction is not needed to describe how the impact of <code>bty_avg</code> on <code>score</code> changes by <code>rank</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>m_bty_rank_inter <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> bty_avg <span class="sc">*</span> rank, <span class="at">data =</span> evals)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>m_bty_rank_inter <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  term                     estimate std.error statistic  p.value
  &lt;chr&gt;                       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                4.10      0.150    27.4    1.80e-98
2 bty_avg                    0.0417    0.0314    1.33   1.84e- 1
3 ranktenure track          -0.0188    0.230    -0.0818 9.35e- 1
4 ranktenured               -0.409     0.182    -2.25   2.52e- 2
5 bty_avg:ranktenure track  -0.0264    0.0463   -0.570  5.69e- 1
6 bty_avg:ranktenured        0.0659    0.0392    1.68   9.38e- 2</code></pre>
</div>
</div>
<hr>
</section>
<section id="to-turn-in" class="level2">
<h2 class="anchored" data-anchor-id="to-turn-in">To Turn In</h2>
</section>
<section id="the-search-for-the-best-model" class="level2">
<h2 class="anchored" data-anchor-id="the-search-for-the-best-model">The search for the best model</h2>
<p>So far, we’ve considered <code>bty_avg</code>, <code>gender</code>, and <code>rank</code> as variables which might predict <code>score</code>. How can we go about finding which variables to use in a model? Which are the best variables? Which are the most important variables? Which are the variables that are not significant?</p>
<p>Start with a full model that predicts professor score based on rank, ethnicity, gender, language of the university where they got their degree, age, proportion of students that filled out evaluations, class size, course level, number of professors, number of credits, average beauty rating, outfit, and picture color.</p>
<section id="q1.-learning-community-q" class="level4">
<h4 class="anchored" data-anchor-id="q1.-learning-community-q">Q1. Learning Community Q</h4>
<p>Describe one thing you learned from someone in your learning community this week (it could be: content, logistical help, background material, R information, etc.) 1-3 sentences.</p>
</section>
<section id="q2.-which-variable-is-worst" class="level4">
<h4 class="anchored" data-anchor-id="q2.-which-variable-is-worst">Q2. Which variable is worst?</h4>
<p>Which variable would you expect to have the highest p-value in this model? Why? <em>Hint:</em> Think about which variable would you expect to not have any association with the professor score. (Use your instincts, not anything technical about the data.)</p>
<p>Check your suspicions from the previous exercise. Include the model output in your response.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>m_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> rank <span class="sc">+</span> ethnicity <span class="sc">+</span> gender <span class="sc">+</span> language <span class="sc">+</span> age <span class="sc">+</span> cls_perc_eval </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>             <span class="sc">+</span> cls_students <span class="sc">+</span> cls_level <span class="sc">+</span> cls_profs <span class="sc">+</span> cls_credits <span class="sc">+</span> bty_avg </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>             <span class="sc">+</span> pic_outfit <span class="sc">+</span> pic_color, <span class="at">data =</span> evals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="q2.-ethnicity" class="level4">
<h4 class="anchored" data-anchor-id="q2.-ethnicity">Q2. Ethnicity</h4>
<p>Interpret the coefficient associated with the ethnicity variable.</p>
</section>
<section id="q3.-pare-down-the-model" class="level4">
<h4 class="anchored" data-anchor-id="q3.-pare-down-the-model">Q3. Pare down the model</h4>
<p>Drop the variable with the highest p-value and re-fit the model. Did the coefficients and significance of the other explanatory variables change? (One of the things that makes multiple regression interesting is that coefficient estimates depend on the other variables that are included in the model.) If not, what does this say about whether or not the dropped variable was collinear with the other explanatory variables?</p>
<p>Should we keep going and remove other variables? Which one(s)? Remove any variables (one at a time) that do not seem to be important to predicting <code>score</code>.</p>
</section>
<section id="q4.-technical-conditions" class="level4">
<h4 class="anchored" data-anchor-id="q4.-technical-conditions">Q4. Technical Conditions</h4>
<p>Verify that the conditions for this model are reasonable using a scatterplot or two. Or feel free to try out a residual plot.</p>
</section>
<section id="q5.-model-interpretation" class="level4">
<h4 class="anchored" data-anchor-id="q5.-model-interpretation">Q5. Model Interpretation</h4>
<p>Based on your final model, describe the characteristics of a professor and course at University of Texas at Austin that would be associated with a high evaluation score.</p>
</section>
<section id="q6.-independence-technical-condition" class="level4">
<h4 class="anchored" data-anchor-id="q6.-independence-technical-condition">Q6. Independence technical condition?</h4>
<p>The original paper describes how these data were gathered by taking a sample of professors from the University of Texas at Austin and including all courses that they have taught. Considering that each row represents a course, could this new information have an impact on any of the conditions of linear regression?</p>
</section>
<section id="q7.-infer-to-what-population" class="level4">
<h4 class="anchored" data-anchor-id="q7.-infer-to-what-population">Q7. Infer to what population?</h4>
<p>Would you be comfortable generalizing your conclusions to apply to professors generally (at any university)? Why or why not?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">praise</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "You are perfect!"</code></pre>
</div>
</div>
<div id="license">
<p>This is a product of OpenIntro that is released under a <a href="http://creativecommons.org/licenses/by-sa/3.0">Creative Commons Attribution-ShareAlike 3.0 Unported</a>. This lab was written by Mine Çetinkaya-Rundel and Andrew Bray.</p>
</div>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Daniel S. Hamermesh, Amy Parker, Beauty in the classroom: instructors pulchritude and putative pedagogical productivity, <em>Economics of Education Review</em>, Volume 24, Issue 4, August 2005, Pages 369-376, ISSN 0272-7757, 10.1016/j.econedurev.2004.07.013. <a href="http://www.sciencedirect.com/science/article/pii/S0272775704001165">http://www.sciencedirect.com/science/article/pii/S0272775704001165</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Data are from (slightly modified) <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em> (Gelman &amp; Hill, 2007).<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div quarto-reuse="quarto-reuse" class="quarto-appendix-contents"><a rel="license" href="https://creativecommons.org/licenses/by/4.0/">https://creativecommons.org/licenses/by/4.0/</a></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left"><a href="https://hardin47.netlify.app/research/"></a> <a href="https://hardin47.netlify.app/resume.pdf" target="_blank"><i class="fa-solid fa-bookmark"></i></a> <a href="mailto:jo.hardin@pomona.edu" target="_blank"><i class="fa-solid fa-at"></i></a> <a href="https://scholar.google.com/citations?user=c5Y77poAAAAJ&amp;hl=en" target="_blank"><i class="fa-brands fa-google-scholar"></i></a> <a href="https://www.researchgate.net/scientific-contributions/Johanna-Hardin-9764530" target="_blank"><i class="fa-brands fa-researchgate"></i></a><br>
<a href="https://mobile.twitter.com/jo_hardin47" target="_blank"><i class="fa-brands fa-twitter"></i></a> <a href="https://github.com/hardin47" target="_blank"><i class="fa-brands fa-github"></i></a> <a href="https://www.linkedin.com/in/jo-hardin-b91a4b55" target="_blank"><i class="fa-brands fa-linkedin-in"></i></a></div>   
      <div class="nav-footer-center">
        <ul class="footer-items list-unstyled">
    <li class="nav-item">
 <br> © Jo Hardin, 2023 -- <a href="mailto: jo.hardin@pomona.edu">jo.hardin@pomona.edu</a> -- <a href="https://hardin47.netlify.app/">https://hardin47.netlify.app/</a> <br> <br>
Math 58B -- Introduction to Biostatistics -- Pomona College, Claremont, CA <br>
  </li>  
</ul>
      </div>
  </div>
</footer>



</body></html>